### ISSUE TITLE
working with Neo4j database server and php locally

### ISSUE THREAD

**Issue by nkem56** [neo4j-examples/movies-neo4j-php-client#1]
Good day  Sir  Ghlens Nagels, My name is Nkem, I saw your amazing projects on github here on Neo4j database with php. its is really what I want.

https://github.com/neo4j-examples/movies-neo4j-php-client

Please I have install xampp and my php is running locally. I have also installed neo4j graph database and its running locally too.

the public/index.php does not show a working example with php and neo4j server locally.

Please do you have a working a example in php on how to 

1.) create neo4j database  name eg Test_db via php
2.) insert, select, update and delete data from neo4j graph database using php. 

Thanks and waiting to hear from you

Thanks

**Comment by transistive** [comment]
Hello nkem,

Thank you for opening an issue. Do you have provided the correct environment variables?

NEO4J_USER, NEO4J_PASSWORD and NEO4J_DATABASE need to be provided.

Also if you do not see anything when the opening the index file there is probably a deeper issue with your local hosting. If php had ran, there would have been an error.

**Comment by nkem56** [comment]
Thanks for getting back to me @transistive please can you help me at this

https://github.com/neo4j-php/neo4j-php-client/issues/47
Thanks
